services:
  backend:
    build: ./hieutapbackend
    ports:
      - "3000:3000"
    env_file:
      - ./hieutapbackend/.env
    restart: always

  frontend:
    build: ./hieutaptaiwind
    ports:
      - "5173:5173"
    depends_on:
      - backend
